# Generated by Django 4.2.4 on 2023-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Food and Dining', 'Food and Dining'), ('Groceries', 'Groceries'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Rent/Mortgage', 'Rent/Mortgage'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Health and Fitness', 'Health and Fitness'), ('Personal Care', 'Personal Care'), ('Education', 'Education'), ('Gifts and Donations', 'Gifts and Donations'), ('Business Expenses', 'Business Expenses'), ('Insurance', 'Insurance'), ('Taxes', 'Taxes')], max_length=20, unique=True)),
            ],
        ),
    ]
