# Generated by Django 4.2.4 on 2023-10-04 07:00

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model("category", "Category")
    categories = [
        {"name": "Food and Dining"},
        {"name": "Groceries"},
        {"name": "Transportation"},
        {"name": "Utilities"},
        {"name": "Rent/Mortgage"},
        {"name": "Entertainment"},
        {"name": "Travel"},
        {"name": "Shopping"},
        {"name": "Health and Fitness"},
        {"name": "Personal Care"},
        {"name": "Education"},
        {"name": "Gifts and Donations"},
        {"name": "Business Expenses"},
        {"name": "Insurance"},
        {"name": "Taxes"},
    ]
    for category in categories:
        Category.objects.create(**category)


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
