# Generated by Django 4.2.5 on 2023-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending_registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendingregistry",
            name="date",
            field=models.DateField(),
        ),
    ]
