# Generated by Django 4.2.5 on 2023-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending_registry", "0002_alter_lendingregistry_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lendingregistry",
            old_name="date",
            new_name="create_date",
        ),
        migrations.AddField(
            model_name="lendingregistry",
            name="clear_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
