# Generated by Django 4.2.5 on 2023-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending_registry", "0003_rename_date_lendingregistry_create_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lendingregistry",
            name="clear_request",
        ),
        migrations.RemoveField(
            model_name="lendingregistry",
            name="clear_status",
        ),
        migrations.RemoveField(
            model_name="lendingregistry",
            name="initiate_request",
        ),
        migrations.AddField(
            model_name="lendingregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiate Request Pending", "Initiate Request Pending"),
                    ("Active", "Active"),
                    ("Clear Request Pending", "Clear Request Pending"),
                    ("Cleared", "Cleared"),
                ],
                default="Initiate Request Pending",
                max_length=30,
            ),
        ),
    ]
