# Generated by Django 4.2.5 on 2023-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending_registry", "0004_remove_lendingregistry_clear_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendingregistry",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="lendingregistry",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
